--- #YAML:1.0
name:               QDBM_File
version:            1.11
abstract:           Tied access to Quick Database Manager
author:
    - Toshiyuki Yamato <toshiyuki.yamato@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
